FROM python:3.12-slim

WORKDIR /app

ADD requirements.txt .
RUN pip install -r requirements.txt
RUN python -m nltk.downloader stopwords

ADD api/ api/
ADD scripts/ scripts/
ADD tests/ tests/

CMD uvicorn api.main:app --host 0.0.0.0 --port 8000